[build]
  base = ""                  # empty because frontend is the base
  publish = "build"          # React build folder
  command = "npm install && npm run build"

[dev]
  command = "npm start"
  port = 3000
  targetPort = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
