[build]
  base = ""                  # frontend is the base, leave empty
  publish = "build"          # points to frontend/build
  command = "npm install && npm run build"

[dev]
  command = "npm start"
  port = 3000
  targetPort = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
