[build]
  base = "frontend"    # frontend folder is the base
  publish = "build"    # relative to the base
  command = "npm install && npm run build"

[dev]
  command = "npm start"
  port = 3000
  targetPort = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
