[build]
  base = ""                   # Leave empty because frontend folder is base directory in Netlify UI
  publish = "build"           # React build output folder
  command = "npm install && npm run build"

[dev]
  command = "npm start"
  port = 3000
  targetPort = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
