[build]
  base = ""                # Leave empty
  publish = "frontend/build"  # Points directly to your React build output
  command = "npm install && npm run build"

[dev]
  command = "npm start"
  port = 3000
  targetPort = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
